services:
  - type: web
    name: todo-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: %l!8vc^1nqpl!(am3gz6mjnc9i!4-c#q)o!5wlh0k8($ujzq!u
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: your-backend.onrender.com
